### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Web3Foundation** [w3f/Web3-wiki#56]
https://github.com/w3f/research/blob/master/docs/polkadot/ParachainAllocation.md

Broken / hidden link ^ on http://research.web3.foundation/en/latest/polkadot/Token%20Economics/

**Comment by laboon** [comment]
It looks like this was fixed on the research site - Link now goes to http://research.web3.foundation/en/latest/polkadot/Parachain-Allocation/

**Comment by laboon** [comment]
I double-checked, this link no longer occurs anywhere in the source.  I believe this can be closed.
